@baseUrl = http://localhost:3000/api/v1

### Register new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@example.com",
    "password": "Password123",
    "role": "admin"
}

### Login user
# @name loginUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Password123"
}

### Login as admin
# @name loginAdmin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "Password123"
}

### Tokens
@authToken = {{loginUser.response.body.token}}
@adminToken = {{loginAdmin.response.body.token}}

### Get current user (me)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{authToken}}
Content-Type: application/json
