@baseUrl = http://localhost:3000/api/v1

### Create new user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "dcs",
    "email": "tester3@example.com",
    "password_hash": "hashed_password",
    "role": "admin",
    "cash_balance": 1000451  
}

### Get user by ID
GET {{baseUrl}}/users/68547ebd-baaf-4054-b04e-fee9507b11bd
Content-Type: application/json
